FROM python:3.12.3-slim-bullseye

# Set working directory
WORKDIR /app

# Copy files into the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt \
    && python -m nltk.downloader punkt stopwords wordnet punkt_tab

# Expose Flask port
EXPOSE 5000

# Run the app
CMD ["python", "app.py"]











# # Use an official Python image as the base
# FROM python:3.12

# # Set the working directory inside the container
# WORKDIR /app

# # Copy the application files
# COPY . .

# # Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# # Download necessary NLTK data
# RUN python -m nltk.downloader punkt stopwords wordnet

# # Expose the Flask port
# EXPOSE 5000

# # Define the command to run the Flask app
# CMD ["python", "app.py"]



